version: '3.1'

services:

  wordpress:
    build: .
    container_name: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - $PWD:/var/www/html/wp-content/plugins/wp-sacloud-webaccel

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - $PWD/.data:/var/lib/mysql
